# Generated by Django 5.2.5 on 2025-11-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRepoGoalsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Repo Goals',
                'verbose_name_plural': 'Repo Goals',
                'managed': False,
            },
        ),
    ]
