# Generated by Django 5.2.5 on 2025-11-21 05:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_repo_first_commit_date'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('goal_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('repo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repo_goal', to='accounts.repo')),
            ],
        ),
    ]
