# Generated by Django 5.2.5 on 2025-11-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_repogoal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminrepogoalsview',
            options={'managed': False, 'verbose_name': 'Set Repo Goals', 'verbose_name_plural': 'Set Repo Goals'},
        ),
        migrations.AddField(
            model_name='repogoal',
            name='org_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
