# Generated by Django 5.2.5 on 2025-11-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_adminrepogoalsview_options_repogoal_org_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='goal-analysis', max_length=100)),
                ('prompt', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('used_count', models.IntegerField(default=0)),
            ],
        ),
    ]
