# Generated by Django 5.2.5 on 2025-11-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goalprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='repogoal',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
