# Generated by Django 5.2.5 on 2025-11-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_repogoal_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repogoal',
            name='org_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='repogoal',
            name='repo_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
