# Generated by Django 5.2.5 on 2025-11-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_repogoal_org_name_alter_repogoal_repo_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoalPrompt',
        ),
    ]
