# Generated by Django 5.2.5 on 2025-11-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_delete_goalprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='repogoal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
