# Generated by Django 5.2.5 on 2025-11-25 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_repo_first_commit_date'),
        ('goals', '0008_repogoal_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repogoal',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='repogoal',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='repogoal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='repogoal',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_goals', to='accounts.repo'),
        ),
    ]
