# Generated by Django 5.2.1 on 2025-05-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechange',
            name='additions_with_line_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filechange',
            name='deletions_with_line_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
