# Generated by Django 5.2.1 on 2025-05-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_filechange_additions_with_line_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechange',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filechange',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
