# Generated by Django 5.2.1 on 2025-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_filechange_is_rated_filechange_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filechange',
            name='additions',
        ),
        migrations.RemoveField(
            model_name='filechange',
            name='additions_with_line_numbers',
        ),
        migrations.RemoveField(
            model_name='filechange',
            name='deletions',
        ),
        migrations.RemoveField(
            model_name='filechange',
            name='deletions_with_line_numbers',
        ),
        migrations.RemoveField(
            model_name='filechange',
            name='is_rated',
        ),
        migrations.AddField(
            model_name='filechange',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
