# Generated by Django 5.2.1 on 2025-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_filechange_additions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechange',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
