# Generated by Django 5.2.1 on 2025-05-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_filechange_is_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filechange',
            name='is_rated',
        ),
        migrations.RemoveField(
            model_name='filechange',
            name='rating',
        ),
    ]
