# Generated by Django 5.2.1 on 2025-05-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_filechange_is_rated_remove_filechange_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechange',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
