# Generated by Django 5.2.1 on 2025-05-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_filechange_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommit',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
