# Generated by Django 5.2.1 on 2025-05-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_gitcommit_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommit',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
