# Generated by Django 5.2.1 on 2025-05-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_gitcommit_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='github_token',
            field=models.CharField(blank=True, db_column='github_token', max_length=255, null=True),
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='github_token',
            new_name='_github_token',
        ),
    ]
