# Generated by Django 5.2.1 on 2025-05-30 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_userprofile__github_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('last_run_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
