# Generated by Django 5.2 on 2025-05-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_scriptrunlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptrunlog',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
