# Generated by Django 5.2.1 on 2025-05-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_scriptrunlog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='github_token',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
