# Generated by Django 5.2.1 on 2025-06-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_userprofile_github_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='github_token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_github_token',
            field=models.BinaryField(blank=True, db_column='github_token', max_length=255, null=True),
        ),
    ]
