# Generated by Django 5.2.1 on 2025-06-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_userprofile_github_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='_github_token',
            field=models.CharField(blank=True, db_column='github_token', max_length=255, null=True),
        ),
    ]
