# Generated by Django 5.2.1 on 2025-06-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_userprofile__github_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='_github_token',
            field=models.TextField(blank=True, db_column='github_token', max_length=500, null=True),
        ),
    ]
