# Generated by Django 5.2.1 on 2025-06-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_userprofile__github_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='_github_token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_token',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
