# Generated by Django 5.2.1 on 2025-06-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_userprofile__github_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='github_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
