# Generated by Django 5.2.1 on 2025-06-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_userprofile_github_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitcommit',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
