# Generated by Django 5.2.1 on 2025-06-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_gitcommit_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitcommit',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
