# Generated by Django 5.2.3 on 2025-07-26 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_gitcommit_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('commit_rated_count', models.IntegerField(default=0)),
                ('accuracy', models.TextField(default='')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='accounts.gitcommit')),
            ],
        ),
    ]
