# Generated by Django 5.2.3 on 2025-07-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLeaderboardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Leaderboard',
                'verbose_name_plural': 'Leaderboard',
                'managed': False,
            },
        ),
    ]
