# Generated by Django 5.2.3 on 2025-07-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_adminleaderboardview'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptrunlog',
            name='run_count',
            field=models.IntegerField(default=0),
        ),
    ]
