# Generated by Django 5.2 on 2025-08-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_scriptrunlog_run_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptrunlog',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
