# Generated by Django 5.2.4 on 2025-08-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_scriptrunlog_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
