# Generated by Django 5.2.4 on 2025-08-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_userprofile_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
