 
# Generated by Django 5.2.5 on 2025-08-14 18:22
 


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_userprofile_github_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='github_token_expiry',
        ),
    ]
