# Generated by Django 5.2.4 on 2025-08-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_bug_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCommitSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Daily Commit Summary',
                'verbose_name_plural': 'Daily Commit Summary',
                'managed': False,
            },
        ),
    ]
