# Generated by Django 5.2.5 on 2025-08-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_dailycommitsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='accuracy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
