# Generated by Django 5.2.5 on 2025-08-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_prompt_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommit',
            name='repo_type',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend')], default='Backend', max_length=20),
        ),
    ]
