# Generated by Django 5.2.5 on 2025-08-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_gitcommit_repo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitcommit',
            name='repo_type',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend')], default='Unknown', max_length=20),
        ),
    ]
