# Generated by Django 5.2.5 on 2025-08-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_gitcommit_repo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitcommit',
            name='repo_type',
        ),
        migrations.AddField(
            model_name='gitcommit',
            name='commit_type',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Fullstack', 'Fullstack'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
    ]
