# Generated by Django 5.2.4 on 2025-08-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_remove_gitcommit_repo_type_gitcommit_commit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitcommit',
            name='author_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
