# Generated by Django 5.2.5 on 2025-08-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_remove_gitcommit_repo_type_gitcommit_commit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitcommit',
            name='commit_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
