# Generated by Django 5.2.4 on 2025-08-29 06:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_gitcommit_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, help_text='List of possible commit names/emails this user might use', size=None),
        ),
    ]
