# Generated by Django 5.2.5 on 2025-08-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_gitcommit_commit_type'),
        ('accounts', '0037_userprofile_aliases'),
    ]

    operations = [
    ]
