# Generated by Django 5.2.4 on 2025-09-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_merge_20250829_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommit',
            name='is_merge',
            field=models.BooleanField(default=False),
        ),
    ]
