# Generated by Django 5.2.5 on 2025-09-04 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_gitcommit_is_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='commit',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='start_date',
        ),
        migrations.AddField(
            model_name='prompt',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
