# Generated by Django 5.2.4 on 2025-09-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_remove_prompt_commit_remove_prompt_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommit',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
