# Generated by Django 5.2.5 on 2025-09-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_remove_prompt_commit_remove_prompt_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
