# Generated by Django 5.2.4 on 2025-09-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_prompt_created_date'),
        ('accounts', '0041_gitcommit_url'),
    ]

    operations = [
    ]
