# Generated by Django 5.2.4 on 2025-09-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_merge_20250909_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitcommit',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gitcommit',
            name='author_email',
            field=models.CharField(blank=True, null=True),
        ),
    ]
