# Generated by Django 5.2.5 on 2025-09-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_gitcommit_author_alter_gitcommit_author_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitcommit',
            old_name='raw_data',
            new_name='raw_gpt_output',
        ),
        migrations.AddField(
            model_name='gitcommit',
            name='rating_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
