# Generated by Django 5.2.5 on 2025-09-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_rename_raw_data_gitcommit_raw_gpt_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommit',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
