# Generated by Django 5.2.4 on 2025-09-12 10:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_gitcommit_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alias_access_token',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Multiple GitHub tokens for fetching commits', size=None),
        ),
    ]
