# Generated by Django 5.2.5 on 2025-09-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_userprofile_alias_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommit',
            name='is_revert',
            field=models.BooleanField(default=False),
        ),
    ]
