# Generated by Django 5.2.5 on 2025-09-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_gitcommit_is_revert'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommit',
            name='suggested_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
