# Generated by Django 5.2.5 on 2025-09-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_gitcommit_suggested_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommit',
            name='message_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
