# Generated by Django 5.2.5 on 2025-10-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_gitcommit_message_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProjectMetricsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Project Metrics',
                'verbose_name_plural': 'Project Metrics',
                'managed': False,
            },
        ),
    ]
