# Generated by Django 5.2.5 on 2025-10-15 08:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last login of the user'),
        ),
    ]
