# Generated by Django 5.2.4 on 2025-10-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_userprofile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='repo_name',
            field=models.CharField(max_length=255),
        ),
    ]
