# Generated by Django 5.2.4 on 2025-10-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_alter_repo_repo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='repo_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
