# Generated by Django 5.2.4 on 2025-10-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alter_repo_repo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bytequest_employee_id',
            field=models.CharField(blank=True, help_text='Internal employee ID for ByteQuest.', max_length=20, null=True, unique=True, verbose_name='ByteQuest Employee ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='razorpay_employee_id',
            field=models.CharField(blank=True, help_text='Employee ID as recognized by RazorpayX Payroll.', max_length=20, null=True, unique=True, verbose_name='Razorpay Employee ID'),
        ),
    ]
