# Generated by Django 5.2.5 on 2025-10-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_userprofile_bytequest_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='repo_name',
            field=models.CharField(max_length=255),
        ),
    ]
