# Generated by Django 5.2.5 on 2025-10-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_alter_repo_repo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='branches',
            field=models.IntegerField(default=0),
        ),
    ]
