# Generated by Django 5.2.5 on 2025-10-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_repo_branches'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repo',
            unique_together={('repo_name', 'org_name')},
        ),
    ]
