# Generated by Django 5.2.5 on 2025-10-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
