# Generated by Django 5.2.5 on 2025-10-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_alter_branch_created_at_alter_branch_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='last_commit',
        ),
    ]
