# Generated by Django 5.2.7 on 2025-11-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_employeeattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ignore_missed_checkin',
            field=models.BooleanField(default=False, help_text='Exclude this user from missed check-in notifications.'),
        ),
    ]
