# Generated by Django 5.2.7 on 2025-11-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_alter_userprofile_ignore_missed_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ignore_missed_checkin',
            field=models.BooleanField(default=False, help_text='Exclude this user from missed check-in notifications.'),
        ),
    ]
