# Generated by Django 5.2.5 on 2025-11-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_userprofile_google_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='first_commit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
