# Generated by Django 5.2.8 on 2025-11-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_repo_first_commit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommit',
            name='ai_generated_score',
            field=models.IntegerField(blank=True, help_text='Estimated percentage of the code changes generated by AI (0-100).', null=True, verbose_name='AI Code Percentage'),
        ),
    ]
