# Generated by Django 5.2.5 on 2025-12-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_gitcommit_ai_generated_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='accounts.repo'),
        ),
    ]
