# Generated by Django 5.2.5 on 2025-12-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_bug_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
