# Generated by Django 5.2.5 on 2025-12-24 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_userprofile_date_of_joining_userprofile_dob_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bytequest_employee_id',
            field=models.CharField(blank=True, help_text='Internal employee ID for ByteQuest.', max_length=20, null=True, verbose_name='ByteQuest Employee ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='razorpay_employee_id',
            field=models.CharField(blank=True, help_text='Employee ID as recognized by RazorpayX Payroll.', max_length=20, null=True, verbose_name='Razorpay Employee ID'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('bytequest_employee_id__isnull', True), _negated=True), fields=('bytequest_employee_id',), name='unique_bytequest_employee_id'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('razorpay_employee_id__isnull', True), _negated=True), fields=('razorpay_employee_id',), name='unique_razorpay_employee_id'),
        ),
    ]
