# Generated by Django 5.2.5 on 2025-12-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_alter_userprofile_bytequest_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='unique_bytequest_employee_id',
        ),
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='unique_razorpay_employee_id',
        ),
    ]
