import logging
import re
import time
from datetime import datetime, timedelta
from django.core.management.base import BaseCommand
from django.utils.timezone import now, make_aware
from django.db.models import Count
from openai import OpenAI, RateLimitError
from django.conf import settings
from accounts.models import GitCommit, Prompt, ScriptRunLog, FileChange 
import json  

 
logger = logging.getLogger('ai_code_analyzer_v2')
client = OpenAI(api_key=settings.OPENAI_API_KEY)

 
def analyze_patch_with_admin_prompt(commit_hash, patch_content, admin_prompt_text):
    if not patch_content or len(patch_content.strip()) < 50:
        return 0 
    system_instruction = (
        "You are an expert software engineering productivity analyst. Your task is to analyze the provided code patch. "
        "Estimate the percentage of the new/modified code that appears to be boilerplate, highly structured, or typically generated by an AI assistant (like Copilot or ChatGPT). "
        "Your FINAL and ONLY output must be a strict JSON object in this exact format: { \"ai_code_percentage\": number, \"reason\": string }. "
        "The reason must be 2–3 lines and MUST clearly justify why this percentage makes sense, based strictly on patch patterns: "
        "repetition, boilerplate structure, structured logic flow, variable/func naming fingerprints, scaffolding, formatting symmetry, or AI-style code generation style."
    )
    user_prompt = (
        f"Analyze the following Git patch and provide the percentage + reason as JSON.\n\n"
        f"COMMIT HASH: {commit_hash[:7]}\n"
        f"PATCH:\n{patch_content}"
    )
    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo", 
            messages=[
                {"role": "system", "content": system_instruction},
                {"role": "user", "content": user_prompt}
            ],
            max_tokens=200,
            temperature=0.0
        )
        gpt_output = response.choices[0].message.content.strip()

        try:
            parsed_json = json.loads(gpt_output)
            score = parsed_json.get("ai_code_percentage")
            reason = parsed_json.get("reason")
            if score is not None and isinstance(score, int):
                return {"score": min(100, max(0, score)), "reason": (reason or "").strip()}
            logger.warning(f"GPT return JSON but missing keys: {gpt_output}")
            return None
        except json.JSONDecodeError:
            score_match = re.search(r'\d+', gpt_output)
            if score_match:
                score = int(score_match.group(0))
                logger.warning(f"JSON Decode failed, fell back to number parsing: {score} for {commit_hash[:7]}")
                return {"score": score, "reason": ""}
            logger.warning(f"GPT returned unparsable score (not JSON, not pure number): '{gpt_output}' for {commit_hash[:7]}")
            return None
    except RateLimitError:
        raise
    except Exception as e:
        logger.exception(f"Error during GPT analysis for {commit_hash[:7]}: {e}")
        return None
 
class Command(BaseCommand):
    help = "Analyzes Git commits for AI percentage using the admin-defined Prompt content."

    def add_arguments(self, parser):
         
        parser.add_argument('--debug',action='store_true',help='Run in debug mode (bypass time restrictions)',)
        parser.add_argument('--user_id',type=int,help='Analyze commits for a specific user ID only',)
        parser.add_argument('--date',type=str,help='Analyze commits for a specific date (YYYY-MM-DD)',)
        parser.add_argument('--start-date',type=str,help='Start date for date range (YYYY-MM-DD)',)
        parser.add_argument('--end-date',type=str,help='End date for date range (YYYY-MM-DD)',)
        parser.add_argument('--limit',type=int,default=50,help='Maximum number of unanalyzed commits to process.',)

    def handle(self, *args, **kwargs):
        analyzed_count = 0
        limit = kwargs.get('limit', 50)
        debug_mode = kwargs.get('debug', False)
        if debug_mode:
            print("Running in DEBUG mode: High verbosity and no time restrictions")
            logger.setLevel(logging.DEBUG)  
        else:
            logger.setLevel(logging.INFO)    
        print("Running scheduled GPT AI Code Analysis job using Admin Prompt...")
        log, _ = ScriptRunLog.objects.get_or_create(name="ai_code_analyzer_v2")
        log.run_count += 1
        log.last_run_at = now()
        log.logs = f"Execution started at: {now().strftime('%Y-%m-%d %H:%M:%S')}\nRun count: {log.run_count}"
        log.save()
        latest_prompt = (
            Prompt.objects.filter(type="commit_rating")
            .exclude(prompt__isnull=True)
            .order_by("-created_date", "-id")
            .first()
        )
        if not latest_prompt or not latest_prompt.prompt:
            error_msg = "No active prompt. Cannot proceed with analysis."
            print(error_msg)
            logger.error(error_msg)
            log.logs += f"\n{error_msg}"
            log.save()
            return
        admin_prompt_text = latest_prompt.prompt
        print(f"Found Admin Prompt: {admin_prompt_text[:50]}...")
        target_date = (now() - timedelta(days=1)).date()
        start_date = None
        end_date = None
        if kwargs.get("date"):
            try:
                target_date = datetime.strptime(kwargs.get("date"), "%Y-%m-%d").date()
            except ValueError:
                pass
        elif kwargs.get("start_date") and kwargs.get("end_date"):
            try:
                start_date = datetime.strptime(kwargs.get("start_date"), "%Y-%m-%d").date()
                end_date = datetime.strptime(kwargs.get("end_date"), "%Y-%m-%d").date()
            except ValueError:
                pass
        commits_qs = GitCommit.objects.filter(ai_generated_score__isnull=True ).annotate(num_files=Count('file_changes')).filter(num_files__gt=0).exclude(message__startswith="Merge").exclude(message__startswith="Revert").exclude(is_merge=True).exclude(is_revert=True).exclude(user__isnull=True).order_by("date")
        if start_date and end_date:
            commits_qs = commits_qs.filter(date__date__range=[start_date, end_date])
        else:
            commits_qs = commits_qs.filter(date__date=target_date)
        if kwargs.get("user_id"):
            commits_qs = commits_qs.filter(user__id=kwargs.get("user_id"))
        commits_to_process = commits_qs[:limit]

        while commits_to_process.exists():

            if not commits_to_process.exists():
                print("No unanalyzed commits found. Exiting.")
                return
            print(f"Found {commits_to_process.count()} commits to analyze.")
            for commit in commits_to_process:
                if not commit.user:
                    continue

                if not debug_mode:
                    time.sleep(1) 

                try:
                    print(f"\nProcessing commit {commit.commit_hash[:7]} (author={commit.author})")
                    file_changes = FileChange.objects.filter(commit=commit)
                    total_ai_score_sum = 0
                    total_files_analyzed = 0
                    ai_reason = ""

                    for file_change in file_changes:
                        patch = file_change.changes
                        if patch and len(patch.strip()) > 50:
                            result = analyze_patch_with_admin_prompt(commit.commit_hash, patch, admin_prompt_text)
                            if result and isinstance(result, dict):
                                total_ai_score_sum += result["score"]
                                total_files_analyzed += 1
                                ai_reason = (result.get("reason") or "").strip()
                                logger.debug(f"{file_change.filename[-30:]}: {result['score']}% AI")

                    if total_files_analyzed > 0:
                        average_ai_score = round(total_ai_score_sum / total_files_analyzed)
                        print(f"AI Code Percentage: {average_ai_score}%")
                        analyzed_count += 1
                    else:
                        average_ai_score = 0
                        ai_reason = "AI score was computed from minimal or formatting-only changes."
                        print("AI Code Percentage: 0% (No substantial changes analyzed)")

                    ai_raw_json = {"ai_code_percentage": average_ai_score, "reason": ai_reason}

                    commit.append_ai_analysis(
                        ai_score=average_ai_score,
                        ai_reason=" " + ai_reason,
                        ai_raw_json=ai_raw_json
                    )

                except RateLimitError:
                    print("Script halted due to OpenAI Rate Limit.")
                    log.logs += f"\nStopped due to OpenAI Rate Limit after analyzing {analyzed_count} commits."
                    log.save()
                    return
                except Exception as e:
                    print(f"Error processing commit {commit.commit_hash[:7]}:", str(e))
                    logger.exception(f"Error for commit {commit.commit_hash[:7]}")

            commits_qs = commits_qs.exclude(id__in=[c.id for c in commits_to_process])
            commits_to_process = commits_qs[:limit]
        
        # Summary
        print("\nAI Code Analysis job finished.")
        final_summary = [
            "\n=== EXECUTION SUMMARY ===",
            f"Total commits analyzed for AI percentage: {analyzed_count}",
            f"Completed at: {now().strftime('%Y-%m-%d %H:%M:%S')}",
        ]
        log.logs += "\n" + "\n".join(final_summary)
        log.last_run_at = now()
        log.save()