# Generated by Django 5.2.8 on 2025-12-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeeroTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeero_timesheet_id', models.BigIntegerField(unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('job_id', models.BigIntegerField(blank=True, null=True)),
                ('job_name', models.CharField(blank=True, max_length=255, null=True)),
                ('clock_in_time', models.DateTimeField(blank=True, null=True)),
                ('clock_in_address', models.TextField(blank=True, null=True)),
                ('clock_in_latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('clock_in_longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('clock_out_latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('clock_out_longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeeroUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeero_user_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_employee_id', models.CharField(blank=True, max_length=200, null=True)),
                ('slack_user_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeeroCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=50)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeero.timeerotimesheet')),
            ],
        ),
        migrations.CreateModel(
            name='TimeeroBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeero_break_id', models.BigIntegerField()),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('duration_in_minutes', models.IntegerField(default=0)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeero.timeerotimesheet')),
            ],
        ),
        migrations.AddField(
            model_name='timeerotimesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeero.timeerouser'),
        ),
    ]
