# Generated by Django 5.2.5 on 2025-12-22 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('tasks_text', models.TextField(blank=True)),
                ('updates_text', models.TextField(blank=True)),
                ('commits', models.JSONField(blank=True, default=list)),
                ('code_relevance_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('code_relevance_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.AlterField(
            model_name='timeerobreak',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='timeero.timeerotimesheet'),
        ),
        migrations.AlterField(
            model_name='timeerocustomfield',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='timeero.timeerotimesheet'),
        ),
        migrations.AlterField(
            model_name='timeerotimesheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timeerotimesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='timeero.timeerouser'),
        ),
        migrations.AlterField(
            model_name='timeerouser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='timeerouser',
            index=models.Index(fields=['email'], name='timeero_tim_email_4a10f6_idx'),
        ),
        migrations.AddIndex(
            model_name='timeerouser',
            index=models.Index(fields=['timeero_user_id'], name='timeero_tim_timeero_ef514b_idx'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['user', 'report_date'], name='timeero_dai_user_id_6c6a29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('user', 'report_date')},
        ),
    ]
