from decouple import config

RAZORPAY_BASE_URL = config("RAZORPAY_BASE_URL")

RAZORPAY_PEOPLE_URL = f"{RAZORPAY_BASE_URL}/people"
RAZORPAY_ATTENDANCE_URL = f"{RAZORPAY_BASE_URL}/att"
RAZORPAY_LEAVES_URL = f"{RAZORPAY_BASE_URL}/leaves"
RAZORPAY_PAYSLIPS_URL = f"{RAZORPAY_BASE_URL}/payslips"

RAZORPAY_ENDPOINTS = {
    "people": RAZORPAY_PEOPLE_URL,
    "attendance": RAZORPAY_ATTENDANCE_URL,
    "leaves": RAZORPAY_LEAVES_URL,
    "payslips": RAZORPAY_PAYSLIPS_URL,
}
